> ### **Assignment 2 - Numpy Array Operations** 


# Some intresting numpy function

**NumPy** (Numerical Python) is a python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.
 
 
We will be focusing on some importend functions in numpy such as:

- np.flip
- np.ptp
- np.copy
- np.extract
- np.reciprocal



In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

<IPython.core.display.Javascript object>

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: 

 ·························································································································································································································································································································


[jovian] Updating notebook "tilakrao1/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/tilakrao1/numpy-array-operations


'https://jovian.ml/tilakrao1/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained 
function1 = np.flip
function2 = np.ptp
function3 = np.copy
function4 = np.extract
function5 = np.reciprocal

## Function 1 - np.flip

**flip** function is used to reverse the order of elements in an array along the given axis where the shape of the array is preserved, but the elements are reordered

In [16]:
# Example 1 - working 
a = np.array([[[0, 1],
               [2, 3]],
              
              [[4, 5],
               [6, 7]]])
print("Before fliping\n",a)
b = np.flip(a,0)
print("After flipping the array\n",b)

Before fliping
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
After flipping the array
 [[[4 5]
  [6 7]]

 [[0 1]
  [2 3]]]


It flip the rows of the array

In [19]:
# Example 2 - working
a = np.array([[[0, 1],
               [2, 3]],
              
              [[4, 5],
               [6, 7]]])
print("Before fliping\n",a)
b = np.flip(a,1)
print("After flipping the array\n",b)

Before fliping
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
After flipping the array
 [[[2 3]
  [0 1]]

 [[6 7]
  [4 5]]]


It flips the columns

In [23]:
# Example 3 - breaking (to illustrate when it breaks)
# Example 2 - working
a = np.array([0, 1, 2, 3, 4, 5, 6, 7])
print("Before fliping\n",a)
b = np.flip(a,1)
print("After flipping the array\n",b)

Before fliping
 [0 1 2 3 4 5 6 7]


AxisError: axis 1 is out of bounds for array of dimension 1

In this we can only flip the array(colomn) having least 2 columns in it

TO flip the array  we should check the shaoe of the array

In [24]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "tilakrao1/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/tilakrao1/numpy-array-operations


'https://jovian.ml/tilakrao1/numpy-array-operations'

## Function 2 -np.ptp

This function output the range i.e the difference between the Maximum and the Minimum value in an array

In [25]:
# Example 1 - working
x = np.array([[4, 9, 2, 10],
          [6, 9, 7, 12]])
print(np.ptp(x, axis=1))

[8 6]


it claculate the max - min for each rows

In [28]:
# Example 2 - working
x = np.array([[4, 9, 2, 10],
          [6, 9, 7, 12]])
print(np.ptp(x))

10


when we did not pass the axis parameter it take the min of the first element and max of second array 12-2

In [32]:
# Example 3 - breaking (to illustrate when it breaks)
x = np.array([[4, 9, 2, 10],
          [6, 9, 12]])
print(np.ptp(x, axis=0))

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In this functions aloge the rows sholud have same no. of elements for claculating the ptp if not the fun. will not works


should use the same no. of elements 

In [33]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "tilakrao1/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/tilakrao1/numpy-array-operations


'https://jovian.ml/tilakrao1/numpy-array-operations'

## Function 3 - np.copy

To create the coppy of array

In [35]:
# Example 1 - working
x = np.array([[4, 9, 2, 10],
          [6, 9, 7, 12]])
y = np.copy(x)
print(id(x))
print(id(y))

140456315172704
140456350605024


create the another array of having differnt storage

In [36]:
# Example 2 - working
x = np.array([[4, 9, 2, 10],
          [6, 9, 7, 12]])
print(x)
y = np.copy(x)
print(y)

[[ 4  9  2 10]
 [ 6  9  7 12]]
[[ 4  9  2 10]
 [ 6  9  7 12]]


both have the different id but have same data

In [38]:
# Example 3 - breaking (to illustrate when it breaks)
x = np.array([[4, 9, 2, 10],
          [6, 9, 7, 12]])
y = np.copy(x)
y = y*2
print(x)
print(y)

[[ 4  9  2 10]
 [ 6  9  7 12]]
[[ 8 18  4 20]
 [12 18 14 24]]


while changes in y will not affect the x


to use the funtion when we want to perform the operation that we are not sure 

In [39]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "tilakrao1/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/tilakrao1/numpy-array-operations


'https://jovian.ml/tilakrao1/numpy-array-operations'

## Function 4 - np.extract

It extract the index of the array where the condition is true

In [41]:
# Example 1 - working
a = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

b = np.extract(a % 3 == 0, a)
print(b)

[0 3 6 9]


it returns the  array of index that satisfie the comditions

In [43]:
# Example 2 - working
a = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

b = np.extract(a % 3 != 0, a)
print(b)

[ 1  2  4  5  7  8 10 11]


it returns the 1d array of index

In [44]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10]])

b = np.extract(a % 3 != 0, a)
print(b)

TypeError: unsupported operand type(s) for %: 'list' and 'int'

it break when we use the improper matric (the aray whish have not no. of rows or colums elemt

to return the index of the arrays where the conditions is satisfy

In [45]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "tilakrao1/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/tilakrao1/numpy-array-operations


'https://jovian.ml/tilakrao1/numpy-array-operations'

## Function 5 - np.reciprocal

It reciprocal all the elements and form a new array

In [49]:
# Example 1 - working
x = np.array([4., 9., 2., 10.])
print(np.reciprocal(x))

[0.25       0.11111111 0.5        0.1       ]


All elements of array x is reciprocaled

In [51]:
# Example 2 - working
x = np.array([[4., 9., 2., 10.],
          [6., 9., 7., 12.]])
print(np.reciprocal(x))

[[0.25       0.11111111 0.5        0.1       ]
 [0.16666667 0.11111111 0.14285714 0.08333333]]


It only reciprocal when we use the float datatype in array

In [54]:
# Example 3 - breaking (to illustrate when it breaks)
x = np.array([[4, 9, 2, 10],
          [6, 9, 7, 12]])
print(np.reciprocal(x))

[[0 0 0 0]
 [0 0 0 0]]


Here we use the int data type so it will brake and give array of zeroes

where we wants to reciprocal the each elements of array

In [55]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "tilakrao1/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/tilakrao1/numpy-array-operations


'https://jovian.ml/tilakrao1/numpy-array-operations'

## Conclusion

We've covered the below functions in this notebook:
- np.flip
- np.ptp
- np.copy
- np.extract
- np.reciprocal



## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [56]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "tilakrao1/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/tilakrao1/numpy-array-operations


'https://jovian.ml/tilakrao1/numpy-array-operations'